<Description>
   ABQcaeG.exe / rank 0 / thread 0  encountered an unhandled exception

</Description>

<Context>
   ABQcaeG
</Context>

<Callstack>
  1)  KERNELBASE.dll              RaiseException                          
  2)  VCRUNTIME140_1.dll          _NLG_Return2                            
  3)  ntdll.dll                   RtlCaptureContext2                      
  4)  ABQcaeG.exe               unknown                                 
</Callstack>

<Memory>
   <Current>            0 GB </Current>
   <Resident>           0 GB </Resident>
   <Physical>          63 GB </Physical>
   <Limit>              0 GB </Limit>
   <Accessible>        63 GB </Accessible>
   <Available>         30 GB </Available>
   <Allocator>            DL </Allocator>
</Memory>

<Swap>
       <Size>          79 GB </Size>
       <Used>          67 GB </Used>
       <Free>          12 GB </Free>
</Swap>

<Directories>
  <current> C:\Stuff\SMM\PRS-Code-Git\ODE-Python\ModelDBs </current> <free>    207 GB </free>   <used>    263 GB </used> 
     <temp> C:\Users\ajbarcio\AppData\Local\Temp </temp>    <free>    207 GB </free>
</Directories>

<Installation>
</Installation>

